apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: invest-beta-react-alpha-v1
  name: invest-beta-react-alpha-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: invest-beta-react-alpha-v1
  template:
    metadata:
      labels:
        run: invest-beta-react-alpha-v1
    spec:
      containers:
      - image: gcr.io/investbeta/invest-beta-react-alpha-v1:latest
        name: invest-beta-react-alpha-v1
        ports:
        - containerPort: 80