kind: Service
apiVersion: v1
metadata:
  name: invest-beta-frontend-v2
spec:
  selector:
     run: invest-beta-react-alpha-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer